[package]
name = "fft_resample"
description = "Basic upsampling using FFT"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
edition = "2018"


[dependencies]
rustfft = "6.0.1"

[dev-dependencies]
hound = "3.4.0"